# PERKS
USER_OVERKILL: False

# GUNS
ASSAULT_RIFLES: True
SMGS: True
LMGS: True
SHOTGUNS: True
TACTICAL_RIFLES: True
MARKSMEN_RIFLES: True
SNIPER_RIFLES: True
MELEE_PRIMARY: True
MELEE_SECONDARY: True
PISTOLS: True
ROCKET_LAUNCHERS: True