Assault Rifle: true
Light Machine Gun: true
Marksmen Rifle: true
Melee Primary: true
Melee Secondary: true
Pistol: true
Rocket Launcher: true
Shotgun: true
Sniper Rifle: true
Submachine Gun: true
Tactical Rifle: true
Use_Overkill: true
