# PERKS
Use_Overkill: False

# GUNS
Assault_Rifles: True
Submachine_Guns: True
Light_Machine_Guns: True
Shotguns: True
Tactical_Rifle: True
Marksmen_Rifles: True
Sniper_Rifles: True
Melee_Primary: True
Melee_Secondary: True
Pistols: True
Rocket_Launchers: True