Assault_Rifles: true
Light_Machine_Guns: true
Marksmen_Rifles: true
Melee_Primary: true
Melee_Secondary: true
Pistols: true
Rocket_Launchers: true
Shotguns: true
Sniper_Rifles: true
Submachine_Guns: true
Tactical_Rifle: true
Use_Overkill: true
